1654772504806	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1654773748760	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1654773748760	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654773748768	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1654773748775	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654773814181	Sync.SyncScheduler	DEBUG	Woke from sleep.
1654773814199	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1654773814199	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1654773814201	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654773816199	Sync.Service	DEBUG	User-Agent: Firefox/101.0 (Linux x86_64) FxSync/1.103.0.20220602144549.desktop
1654773816200	Sync.Service	INFO	Starting sync at 2022-06-09 13:23:36 in browser session Zw_kJ4J9DoaC
1654773816200	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654773816203	Sync.Status	INFO	Resetting Status.
1654773816203	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1654773816203	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1654773816203	FirefoxAccounts	DEBUG	getOAuthToken enter
1654773816204	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654773816204	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654773816204	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1654773816208	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1654773816208	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1654773816209	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654773816209	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1654773816209	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1654773816209	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654773816209	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1654773816212	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
